### ISSUE TITLE
Handle NoSuchElementException from selenium

### ISSUE THREAD

**Issue by netzulo** [netzulo/qacode#103]
# TODOs

- [ ] catch **NoSuchElementException** raises when searching for selectors
  - [ ] must provide session properties 
    ``` python
    self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fc861cc8f60>
    response = {'sessionId': 'a35ed85e0664cc1a28dbb9ddd5d0a3a8', 'status': 7, 'value': {'message': 'no such element: Unable to locate...r info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.4.0-104-generic x86_64)'}}
    ```
  - [ ] must provide exception properties ( *message + selector* )
    ``` python
    selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".dc-box-ds a[href='/panel/datacenters'] .badge"}
    ``` 

### Tests

*New test must not be added, just passed for exiting tests*
