### ISSUE TITLE
Controls must scroll when not visible but if loaded and not hidden

### ISSUE THREAD

**Issue by netzulo** [netzulo/qacode#108]
# SPECs

Doc : https://stackoverflow.com/questions/20888592/gettext-method-of-selenium-chrome-driver-sometimes-returns-an-empty-string

+ [x] When element it's on visible screen, at exec get_text on element obtains real text , but , if not visible , returns empty value

## TODOs

+ [ ] need something to exec arbitrary JS code for [driver, page, element ]
+ [ ] maybe must to be optional param on **get_text function** , *Check java example before to code*`((JavaScriptExecutor)driver).executeScript("arguments[0].scrollIntoView(true);", element);`

### Tests

+ [ ] an element visible must fail ( *element.get_text(on_screen=True)* ) when use param visible when *it's visible right now*
+ [ ] an element not visible must fail when the problem accesing to him it's : *emtpy get_text string + False property is_visible*
