### ISSUE TITLE
pythonic, naming modules

### ISSUE THREAD

**Issue by netzulo** [netzulo/qacode#110]
# SPECs

- read about this : http://mikegrouchy.com/blog/2012/05/be-pythonic-__init__py.html

## TODOs

- [x] be more pythonic writing **__init__.py** files
- [x] import subpackages on each **__init__.py** file

### Tests

- [x] ~do a `dir(package_name)` and *get all subpackage names* on each **__init__.py** file~
