### ISSUE TITLE
add headless for : chrome, firefox, opera

### ISSUE THREAD

**Issue by netzulo** [netzulo/qacode#140]
## TODOs

- [x] headless mode for **chrome**
- [x] headless mode for **firefox**
- [x] headless mode for **opera**

### Tests

- [x] tests local headless mode for **chrome**
- [x] tests remote headless mode for **chrome**
- [x] tests local headless mode for **firefox**
- [x] tests remote headless mode for **firefox**
- [x] headless local mode for **opera**
- [x] headless remote amode for **opera**
