### ISSUE TITLE
Implement all posible remote browsers by Selenium

### ISSUE THREAD

**Issue by netzulo** [netzulo/qacode#183]
# Documentation

http://selenium-python.readthedocs.io/api.html#desired-capabilities

``` python
ANDROID = {'platform': 'ANDROID', 'browserName': 'android', 'version': ''}
CHROME = {'platform': 'ANY', 'browserName': 'chrome', 'version': ''}
EDGE = {'platform': 'WINDOWS', 'browserName': 'MicrosoftEdge', 'version': ''}
FIREFOX = {'acceptInsecureCerts': True, 'browserName': 'firefox', 'marionette': True}
HTMLUNIT = {'platform': 'ANY', 'browserName': 'htmlunit', 'version': ''}
HTMLUNITWITHJS = {'platform': 'ANY', 'browserName': 'htmlunit', 'version': 'firefox', 'javascriptEnabled': True}
INTERNETEXPLORER = {'platform': 'WINDOWS', 'browserName': 'internet explorer', 'version': ''}
IPAD = {'platform': 'MAC', 'browserName': 'iPad', 'version': ''}
IPHONE = {'platform': 'MAC', 'browserName': 'iPhone', 'version': ''}
OPERA = {'platform': 'ANY', 'browserName': 'opera', 'version': ''}
PHANTOMJS = {'platform': 'ANY', 'browserName': 'phantomjs', 'version': '', 'javascriptEnabled': True}
SAFARI = {'platform': 'MAC', 'browserName': 'safari', 'version': ''}
WEBKITGTK = {'platform': 'ANY', 'browserName': 'MiniBrowser', 'version': ''}
```
---

## TODOs

- [ ] android
- [x] chrome
- [x] firefox
- [x] iexplorer
- [x] edge
- [ ] htmlunit
- [ ] htmlunitwithjs
- [ ] ipad
- [ ] iphone
- [x] ~phantomjs~ depecated at **selenium 3.12**
- [ ] safari
- [ ] webkitgtk

+ [ ] handle all options for each browser
+ [ ] adjust settings.json to read new properties for each browser 

  - from 
``` python
{
  "bot": {
    ...
    "drivers_names": [
      "chromedriver_32.exe",
      "chromedriver_64.exe",
      "chromedriver_32",
      "chromedriver_64",
      "firefoxdriver_32.exe",
      "firefoxdriver_64.exe",
      "firefoxdriver_64.exe",
      "firefoxdriver_32",
      "phantomjsdriver_32.exe",
      "phantomjsdriver_64.exe",
      "phantomjsdriver_32",
      "phantomjsdriver_64",
      "iexplorerdriver_32.exe",
      "iexplorerdriver_64.exe",
      "edgedriver_32.exe",
      "edgedriver_64.exe",
      "operadriver_32.exe",
      "operadriver_64.exe",
      "operadriver_32",
      "operadriver_64"
    ],
  ...
  }
}
```
  - to 
``` python
{
  "mode": "remote" # local, remote
  "drivers": [
    { 
      "name": "chrome",
      "options": { "headless": True },
      "binaries": {
        "path": "/binaries/"
        "win_32": "chromedriver_32.exe",
        "win_64": "chromedriver_64.exe",
        "lin_32": "chromedriver_32",
        "win_32": "chromedriver_64",
      }
    }
  ]
}
```

**Comment by netzulo** [comment]
rest of ticket it's invalid but improve at browser selection for tests
