### ISSUE TITLE
PageLogged Class

### ISSUE THREAD

**Issue by netzulo** [netzulo/qacode#34]
# TODO

#### Coverage

- [x] coverage fixes for **logger_manager**
- [x] coverage fixes for **bot_config**
- [x] coverage fixes for **nav_base**

## PageBase

+ [x] is_url: check real selenium url with page loaded url

## PageLogged

+ [x] logged status must be loaded with `is_login` method from `page_login`
+ [x] logout: do logout going to **url_logout** property
+ [x] is_logged: check logged state using PageLogin instance

# Tests

+ [x] PageBase | method **is_url** , default params values
+ [x] PageBase | method **is_url** , assert return true
+ [x] PageBase | method **is_url** , assert return false *( no exceptions )*
+ [x] PageBase | method **is_url** , default params values *(except **ignore_raises as FALSE** )*
+ [x] PageBase | method **is_url** , assert return true *(except **ignore_raises as FALSE** )*
+ [x] PageBase | **raises** method **is_url** , assert exception PageException instead of false *(except **ignore_raises as FALSE** )*

+ [x] PageLogged | check **instance OK** 
+ [x] PageLogged | check **login success** status throught `is_logged` property
+ [x] PageLogged | check **login failed** status throught `is_logged` property
+ [x] PageLogged | **raises** page_logged when param **url_logged is none**
+ [x] PageLogged | **raises** page_logged when param **url_logout is none**
+ [x] PageLogged | **raises** **is_logged** when page_login it's not instance of PageLogin class

**Comment by netzulo** [comment]
merget at #106
