### ISSUE TITLE
TODO ControlBase

### ISSUE THREAD

**Issue by netzulo** [netzulo/qacode#70]
# Requisites

+ [x] Must validate at instance class if tag it's HTML valid tag **(ControlBase)** 
+ [x] Must load properies *is_{prop_name}* ( _is_enabled, is_visible, is_selected_ )

## Behaviors

+ HTML: search content text ( _without subtags_ )
+ HTML: search basic attributes
  + [x] ```<tag>``` : must validate atribute **id**  ```<tag id="value"></tag>```
  + [x] ```<tag>``` : must validate atribute **class**  ```<tag class="value"></tag>```

### TODOs

+  [x] Modify **PageBase** to accept elements or ControlBase objects
+  [x] Modify **PageLogin** to use elements or ControlBase objects
+  [x] Modify **tests/functionals/Test*** to make them work again with ``python setup.py test``
