### ISSUE TITLE
add support to Opera Browser + tests

### ISSUE THREAD

**Issue by netzulo** [netzulo/qacode#85]
# TODO

+ [x] knows about ENV name for opera browser driver
   + [x] test about : **"-Dopera.binary="**
   + [x] test about : **"-Dwebdriver.opera.driver="**
+ [x] add new drivers to module **qadrivers**
+ [x] add to one public node and test it manually **FAILED at 12-12-2017**

## Documentation 

http://www.opera.com/es/computer

## Tests

+ [x] test for mode **local** and browser_name **opera**
+ [x] test for mode **remote** and browser_name **opera**
+ [ ] **manual** test for mode **remote** and browser_name **opera** , opening page
+ [ ] **manual** test for mode **remote** and browser_name **opera** , using webelement
+ [ ] **manual** test for mode **remote** and browser_name **opera** , using ControlBase

### Manuals

Need to test combinations for

1. env var command lane **-Dopera.binary=** and **-Dwebdriver.opera.driver=**
 --> 
2. node browser name **opera** and **operablink**
 --> 
3. python remote browser name **opera** and **operablink**

- [ ] var name 1 + node name 1 + python selenium code 1
- [ ] var name 1 + node name 1 + python selenium code 2
- [ ] var name 1 + node name 2 + python selenium code 1
- [ ] var name 1 + node name 2 + python selenium code 2
- [ ] var name 2 + node name 2 + python selenium code 1
- [ ] var name 2 + node name 2 + python selenium code 2
  
## Issues related

- [ ] official opera chromium based https://github.com/operasoftware/operachromiumdriver/issues/9
- [x] qadrivers, update binary from **v0.2.32** to **v0.2.33** https://github.com/netzulo/qadrivers/issues/5

**Comment by netzulo** [comment]
Need to test combinations for

**-Dopera.binary=** **-Dwebdriver.opera.driver=" --> node browser name **opera** and **operablink** --> python remote browser name **opera** and **operablink**

1. [ ] var name 1
2. [ ] var name 2
3. [ ] node name 1
4. [ ] node name 2
5. [ ] python selenium code 1
6. [ ] python selenium code 2

**Comment by netzulo** [comment]
need to check this : https://github.com/netzulo/qadrivers/issues/5

**Comment by netzulo** [comment]
Solution proposed it's 

``` python
#!/usr/bin/env python3
# selenium 3.14.1, Python 3.7.0

from selenium import webdriver

options = webdriver.ChromeOptions()
options.binary_location = "/usr/bin/opera"

# and make sure you have operadriver in PATH
driver = webdriver.Opera(options=options)
driver.get('https://example.com')
print(driver.title)
```

**Comment by netzulo** [comment]
Will be removed all residual code at #269
