### ISSUE TITLE
Install TOX for local python env builds

### ISSUE THREAD

**Issue by netzulo** [netzulo/qacode#88]
# TODO

+ [x] command wich exec `python setup.py test` for each python version at local command line https://github.com/netzulo/qacode/commit/af312f5bd23ab660eb5d4fb6186e5d0fdef9ac77
+ [x] integrate tox with **travis builds** https://github.com/netzulo/qacode/commit/173e6bb0094b5bd61af7eaa5a513a1fdc519a3d8
+ [x] integrate tox with **appveyor builds** https://github.com/netzulo/qacode/commit/3064d0b71eee4f8f14c2b5b36448297cf6b37c8a
