### ISSUE TITLE
more browser tests

### ISSUE THREAD

**Issue by netzulo** [netzulo/qacode#90]
All browser must be opened using qacode local/remote driver and must can be load element as WebElement or as ControlBase classes, and opened using PageBase class to **test all library on all browsers**

# TODO

+ [ ] must be included on a new suite named **suite_xxx_bot_browsers.py** module

_all browser must have one test for each browser_

+ [ ] manual test for **browser_name** , opening page
+ [ ] manual test for **browser_name** , using webelement
+ [ ] manual test for **browser_name** , using ControlBase

## Tests

_mode must be selected from config_

+ [ ] test for **chrome** , opening page
+ [ ] test for **chrome** , using webelement
+ [ ] test for **chrome** , using ControlBase
+ [ ] test for **firefox** , opening page
+ [ ] test for **firefox** , using webelement
+ [ ] test for **firefox** , using ControlBase
+ [ ] test for **phantomjs** , opening page
+ [ ] test for **phantomjs** , using webelement
+ [ ] test for **phantomjs** , using ControlBase
+ [ ] test for **internet explorer** , opening page
+ [ ] test for **internet explorer** , using webelement
+ [ ] test for **internet explorer** , using ControlBase
+ [ ] test for **MicrosoftEdge** , opening page
+ [ ] test for **MicrosoftEdge** , using webelement
+ [ ] test for **MicrosoftEdge** , using ControlBase
+ [ ] test for **opera** , opening page
+ [ ] test for **opera** , using webelement
+ [ ] test for **opera** , using ControlBase
+ [ ] test for **ANDROID** #66
