### ISSUE TITLE
LoggerManager must contain log methods as self

### ISSUE THREAD

**Issue by netzulo** [netzulo/qacode#93]
# TODOs

+ [x] method **self.debug()**
  + [ ] test with key value **'DEBUG'**
+ [x] method **self.info()**
  + [ ] test with key value **'INFO'**
+ [x] method **self.warning()**
  + [ ] test with key value **'WARNING'**
+ [x] method **self.error()**
  + [ ] test with key value **'ERROR'**
+ [x] method **self.critical()**
  + [ ] test with key value **'CRITICAL'**

**Comment by netzulo** [comment]
closed, bad idea...
